### ISSUE TITLE
Darker Depths Biomes not spawning in Strangely Modded

### ISSUE THREAD

**Issue by StrangerSon713** [ItsBlackGear/bgcore#5]
Config allows it, Caves and Cliffs Backport is 5.2 and BGcore is 3.2, I don't know whats wrong.

**Comment by ItsBlackGear** [comment]
do caves and cliffs biomes spawn? or it doesn't allow the spawn of any cave biome?

**Comment by StrangerSon713** [comment]
I saw caves and cliffs biomes, but no darker depths. I ran /locate (above y 40) and it returned nothing, so I made this report. I have since learned of the /locate bug, so am retesting now.

**Comment by StrangerSon713** [comment]
Can confirm this bug is ineligible and should be closed.

**Comment by ItsBlackGear** [comment]
Hmm.. not sure of what may be causing the issue, usually it's because
you're using incompatible versions but the versions that you mention are
indeed compatible, i would suggest to wait for darker depths 1.1 since it
will be compatible with the latest version of bgcore (AKA CaveBiomeAPI)

**Comment by StrangerSon713** [comment]
They did spawn, they were 300 blocks away so I couldn't see them, and /locatebiome didn't work.

**Comment by ItsBlackGear** [comment]
The possible causes are that you could have maybe added darker depths after
creating the world or you may have increased the cave biome size a bit too
much

**Comment by StrangerSon71** [comment]
I think it was just bad luck, the world was created on the latest version and I kept the size at 4

**Comment by ItsBlackGear** [comment]
Pff in that case yeah xD it could be bad luck haha
